config/routes.rb
Rails.application.routes.draw do

  root "tests#index"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users,
             controllers: {sessions: "sessions"} ,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout  }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do 
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :gists, only: %i[show index]
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index]
  resources :user_badges, only: %i[index]
end

app/models/admin.rb
class Admin < User
  validates :name, presence: true
  validates :surname, presence: true
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }
  validate :validate_max_answer, on: :create

  private

  def validate_max_answer
    errors.add(:question) if question.answers.size > 4
  end
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord

  RULES = [["Пройдены все тесты категории", "success_category"], 
             ["Тест пройден с первой попытки", "success_on_first_try"],
             ["Пройдены все тесты уровня", "success_all_level"],
           ].freeze

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges
  validates :title, :img_url, :rule, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  default_scope { order(title: :asc) }
end

app/models/feedback.rb
class Feedback

  include ActiveModel::Model 
  attr_accessor :email, :message

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP } 
  validates :message, presence: true

end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :question
end

app/models/passed_test.rb
class PassedTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates  :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord

  TEST_LEVELS = { 0 => :easy, 1 => :easy, 2 => :medium, 3 => :medium, 4 => :medium}.freeze

  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :test_passages, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :users, through: :test_passages

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :categories, -> (category) {
      joins(:category)
        .where(categories: {title: category})
  }

  def test_level(test)
    TEST_LEVELS[test.level] || :hard
  end
  
  def self.sort_categories(category)
    categories(category).order(title: :desc).pluck(:title)
  end

  validates :level, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :title, presence: true,
                    uniqueness: { scope: :level }

end

app/models/test_passage.rb
class TestPassage < ApplicationRecord

  PASSING_SCORE = 85.freeze
  
  belongs_to :current_question, class_name: 'Question', optional: true
  belongs_to :user
  belongs_to :test
  
  before_validation :before_validation_set_question, on: %i[create update]

  def success?
    percent_correct >= PASSING_SCORE && !time_is_up?
  end
  
  def completed?
    current_question.nil?
  end
  
  def accept!(answer_ids)
    if correct_answer?(answer_ids) && !time_is_up?
      self.correct_questions += 1
    end
    save!
  end

   def total_test_questions
    test.questions.count
  end

  def percent_correct
    (correct_questions.to_f * 100 / total_test_questions).round(2)
  end

  def current_question_number
   test.questions.order(:id).where('id < ?', current_question.id).count + 1
  end

  def before_validation_set_question
      self.current_question = next_question 
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == Array(answer_ids).map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if new_record?
      test.questions.first if test.present?
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def timer_finish
    created_at + test.timer.minutes
  end

  def time_is_up?
    test.timer? && timer_finish.past?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable, 
         :trackable,
         :validatable,
         :confirmable

  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :author_tests, class_name: 'Test', foreign_key: :author_id
  has_many :gists, foreign_key: :author_id, class_name: 'Gist'

  validates :email, presence: true #:name, :surname,
  validates :email, uniqueness: true,
            format: { with: URI::MailTo::EMAIL_REGEXP,
                       message: "Формат почты: name@example.com" }

  def test_by_level(level)
    Test.joins(:passed_tests)
        .where('passed_tests.user_id = ? AND tests.level = ?', id, level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.is_a?(Admin)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge

end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController

  before_action :set_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def edit
  end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to [:admin, @badge], notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to [:admin, @badge]
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :img_url, :rule, :parameter)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @badges = Badge.all
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found
  before_action :authenticate_user!
  before_action :find_test, only: %i[start]

  def index
    @tests = Test.where(ready: true)
  end

  
  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end
  
  private

  def find_test
    @test = Test.find(params[:id])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper 

    ALERTS = {
      notice: "info",
      error: "danger",
      success: "success",
      alert: "warning"
    }
  
  def current_year
    Date.current.year
  end

  def github_url(author, repo)
    link_to 'Проект githab', "https://github.com/#{author}/#{repo}", target: '_blank'
  end

  def flash_alert(flash)
    ALERTS[flash.to_sym] if flash[flash]
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      t('admin.questions.show.edit_question')  
    else
      t('admin.questions.show.new_question')
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
 
end

app/helpers/user_badges_helper.rb
module UserBadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr>    
  <td class='align-middle'>
    <%= image_tag( badge.img_url, size: "20x30", alt: t('.alt_image_tag')) %>
  </td>
  <td class='align-middle'><%= badge.title %></td>
  <td class='align-middle'><%= badge.rule %></td>
  <td class='align-middle'><%= badge.parameter %></td>
  <td class='align-middle'><%= link_to t('admin.actions.show'), admin_badge_path(badge) %></td>
  <td class='align-middle'>
    <%= link_to t('admin.actions.edit'), 
                edit_admin_badge_path(badge),
                data: { badge_id: badge.id }
    %>
  </td>
  <td><%= link_to t('admin.actions.delete'), 
        admin_badge_path(badge), 
        method: :delete,
        data: { confirm: t('admin.actions.confirm') }
      %>
  </td>

</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin,  @badge], local: true do |form| %>
  <%= render "shared/errors", resource: @badge %>

  <p>
    <%= form.label :title %>
    <%= form.text_field :title, id: :badge_title %>
  </p>

  <p>
    <%= form.label :img_url %>
    <%= form.text_field :img_url, id: :badge_img_url %>
  </p>

  <p>
    <%= form.label :rule %>
    <%= form.select :rule, Badge::RULES,
                           prompt: true %>
  </p>

  <p>
    <%= form.label :parameter %>
    <%= form.text_field :parameter, id: :badge_parameter %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/badges/edit.html.erb
<%= render 'form' %>

<%= link_to t('admin.actions.back'), admin_badge_path %>

app/views/admin/badges/index.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6"><h1><%= t('.header') %></h1></div>
  <div class="col-12">
    <div class="row">
      <div class="col-3">
        <%= link_to t('.new_badge'), new_admin_badge_path %>
      </div>
      <%= render 'shared/errors', resource: @badge %>  
    </div>

    <table class="table table-striped mt-3">
      <thead class="table align-middle">
        <tr>
          <th scope="col"><%= t('.badge') %></th>
          <th scope="col"><%= t('.title') %></th>
          <th scope="col"><%= t('.rule') %></th>
          <th scope="col"><%= t('.parameter') %> </th>
          <th scope="col", colspan="3", class="text-center"><%= t('tests.index.actions') %></th>
        </tr>
      </thead>

      <tbody>
          <%= render @badges %>
      </tbody>
    </table>
    
    <div class="col-3">
      <%= link_to t('admin.actions.back'), admin_tests_path %></p>
    </div>
  </div>
</div>

app/views/admin/badges/new.html.erb
<h1><%= t('.header') %></h1>

<%= render 'form' %>

<%= link_to t('admin.actions.back'), admin_badges_path %>

app/views/admin/badges/show.html.erb
<p>
  <strong><%=t('.badge') %>:</strong>
  "<%= @badge.title %>"
</p>

<p>
  <strong><%= t('.rule') %>:</strong>
  <%= @badge.rule %>
</p>
<p>
  <strong><%= t('.parameter') %>:</strong>
  <%= @badge.parameter %>
</p>

<p>
  <strong><%= t('.alt_image_tag') %></strong>
  <%= image_tag( @badge.img_url, size: "20x30", alt: t('.alt_image_tag')) %>
</p>
<%= link_to t('.edit_badge'), edit_admin_badge_path %>
<%= link_to t('admin.actions.back'), admin_badges_path %>

app/views/badges/_badge.html.erb
<tr>    
  <td>
    <%= image_tag( badge.img_url, size: "20x30", alt: t('.alt_image_tag')) %>
  </td>
  <td> 
    <%= badge.title %>
  </td>
  <td>
    <%= badge.rule %>
  </td>
  <td> 
    <%= badge.parameter %>
  </td>
</tr>

app/views/badges/index.html.erb
<div>
  <h3 class="text-center mt-5"><%= t('.header') %></h3>
</div>

<div class="col-12">
  <table class="table table-striped mt-3">
    <thead>
      <tr>
        <th scope="col" class="col-3"><%= t('.badge') %></th>
        <th scope="col" class="col-3"><%= t('.title') %></th>
        <th scope="col" class="col-3"><%= t('.rule') %></th>
        <th scope="col" class="col-3"><%= t('.parameter') %></th>
      </tr>
    </thead>

    <tbody>
        <%= render @badges %>
    </tbody>
  </table>
  <div class="col-3">
      <%= link_to t('admin.actions.back'), user_badges_path %></p>
  </div>
</div>