config/routes.rb
Rails.application.routes.draw do

  root "tests#index"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users,
             controllers: {sessions: "sessions"} ,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout  }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do 
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :gists, only: %i[show index]
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index]
  resources :user_badges, only: %i[index]
end

app/models/admin.rb
class Admin < User
  validates :name, presence: true
  validates :surname, presence: true
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }
  validate :validate_max_answer, on: :create

  private

  def validate_max_answer
    errors.add(:question) if question.answers.size > 4
  end
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord

  RULES = [["Пройдены все тесты категории", "success_category"], 
             ["Тест пройден с первой попытки", "success_on_first_try"],
             ["Пройдены все тесты уровня", "success_all_level"],
           ].freeze

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges
  validates :title, :img_url, :rule, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  default_scope { order(title: :asc) }
end

app/models/feedback.rb
class Feedback

  include ActiveModel::Model 
  attr_accessor :email, :message

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP } 
  validates :message, presence: true

end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :question
end

app/models/passed_test.rb
class PassedTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates  :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord

  TEST_LEVELS = { 0 => :easy, 1 => :easy, 2 => :medium, 3 => :medium, 4 => :medium}.freeze

  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :test_passages, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :users, through: :test_passages

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :categories, -> (category) {
      joins(:category)
        .where(categories: {title: category})
  }

  def test_level(test)
    TEST_LEVELS[test.level] || :hard
  end
  
  def self.sort_categories(category)
    categories(category).order(title: :desc).pluck(:title)
  end

  validates :level, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :title, presence: true,
                    uniqueness: { scope: :level }

end

app/models/test_passage.rb
class TestPassage < ApplicationRecord

  PASSING_SCORE = 85.freeze
  
  belongs_to :current_question, class_name: 'Question', optional: true
  belongs_to :user
  belongs_to :test
  
  before_validation :before_validation_set_question, on: %i[create update]

  def success?
    percent_correct >= PASSING_SCORE && !time_is_up?
  end
  
  def completed?
    current_question.nil?
  end
  
  def accept!(answer_ids)
    if correct_answer?(answer_ids) && !time_is_up?
      self.correct_questions += 1
    end
    save!
  end

   def total_test_questions
    test.questions.count
  end

  def percent_correct
    (correct_questions.to_f * 100 / total_test_questions).round(2)
  end

  def current_question_number
   test.questions.order(:id).where('id < ?', current_question.id).count + 1
  end

  def before_validation_set_question
      self.current_question = next_question 
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == Array(answer_ids).map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if new_record?
      test.questions.first if test.present?
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def timer_finish
    created_at + test.timer.minutes
  end

  def time_is_up?
    test.timer? && timer_finish.past?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable, 
         :trackable,
         :validatable,
         :confirmable

  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :author_tests, class_name: 'Test', foreign_key: :author_id
  has_many :gists, foreign_key: :author_id, class_name: 'Gist'

  validates :email, presence: true #:name, :surname,
  validates :email, uniqueness: true,
            format: { with: URI::MailTo::EMAIL_REGEXP,
                       message: "Формат почты: name@example.com" }

  def test_by_level(level)
    Test.joins(:passed_tests)
        .where('passed_tests.user_id = ? AND tests.level = ?', id, level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.is_a?(Admin)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper 

    ALERTS = {
      notice: "info",
      error: "danger",
      success: "success",
      alert: "warning"
    }
  
  def current_year
    Date.current.year
  end

  def github_url(author, repo)
    link_to 'Проект githab', "https://github.com/#{author}/#{repo}", target: '_blank'
  end

  def flash_alert(flash)
    ALERTS[flash.to_sym] if flash[flash]
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      t('admin.questions.show.edit_question')  
    else
      t('admin.questions.show.new_question')
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
 
end

app/helpers/user_badges_helper.rb
module UserBadgesHelper
end

app/views/admin/_navbar.html.erb
<nav class="navbar navbar-light bg-info rounded">
  <div class="container">
    <%= link_to t('layouts.header'), root_path, class: 'navbar-brand' %>
    <span class="navbar-text">
      <%= link_to t('.badge'), admin_badges_path, class: "btn btn-outline-secondary text-light" %>
      <% if Gist.any? %>
        <%= link_to t('.gists'), admin_gists_path, class: "btn btn-outline-secondary text-light", target: :_blank %>
      <% end %>

      <%= t('shared.navbar.welcome') %><b><%= current_user.email %></b> 
        <%= link_to t('shared.navbar.logout'), destroy_user_session_path, method: :delete, class: "btn btn-outline-light text-light" %>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('.panel') %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= render 'admin/navbar' %>
      <%= render 'shared/flash' %> 
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flash' %> 
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
  	<h2><%= t('.header', count: resource.errors.count) %>:</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
 <div class="alert alert-<%= flash_alert(key) %>" role="alert">
  <%= content_tag :p, sanitize(message) %>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div align="center">
  <br>
  <%= current_year %>
  <br>
  <%= github_url("vik1972", "testguru") %><br>
  Тест Гуру <br>
  <%= link_to 'Учебный проект в онлайн-школе Thinknetica', 'https://thinknetica.com', target:'blank' %>
  <p><%= link_to 'Обратная связь', new_feedback_path %></p>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-info rounded">
  <div class="container">
      <%= link_to t('.header'), root_path, class: 'navbar-brand' %>
      <%= link_to t('.my_badge'), user_badges_path, class: 'navbar-brand' %>

    <span class="navbar-text">
      <% if user_signed_in? %>

        <% if  current_user.admin? %>
          <%= link_to t('layouts.admin.panel'), admin_tests_path, class: "btn btn-outline-info " %>
        <% end %>

        <%= t('.welcome') %><b><%= current_user.email %></b> 
        <%= link_to t('.logout'), destroy_user_session_path, method: :delete, class: "btn btn-outline-light text-light" %>
      <% else %>
        <%= link_to t('.sign_up'), new_user_registration_path, class: "btn btn-outline-light text-light" %>
        <%= link_to t('.sign_in'), new_user_session_path, class: "btn btn-outline-light text-light" %>
      <% end %>
    </span>
  </div>
</nav>