config/routes.rb
Rails.application.routes.draw do

  root "tests#index"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users,
             controllers: {sessions: "sessions"} ,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout  }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do 
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :gists, only: %i[show index]
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: %i[index]
  resources :user_badges, only: %i[index]
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates  :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord

  PASSING_SCORE = 85.freeze
  
  belongs_to :current_question, class_name: 'Question', optional: true
  belongs_to :user
  belongs_to :test
  
  before_validation :before_validation_set_question, on: %i[create update]

  def success?
    percent_correct >= PASSING_SCORE && !time_is_up?
  end
  
  def completed?
    current_question.nil?
  end
  
  def accept!(answer_ids)
    if correct_answer?(answer_ids) && !time_is_up?
      self.correct_questions += 1
    end
    save!
  end

   def total_test_questions
    test.questions.count
  end

  def percent_correct
    (correct_questions.to_f * 100 / total_test_questions).round(2)
  end

  def current_question_number
   test.questions.order(:id).where('id < ?', current_question.id).count + 1
  end

  def before_validation_set_question
      self.current_question = next_question 
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == Array(answer_ids).map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if new_record?
      test.questions.first if test.present?
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def timer_finish
    created_at + test.timer.minutes
  end

  def time_is_up?
    test.timer? && timer_finish.past?
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :set_test_passage, only: %i[show update result gist]

  def show
      redirect_to result_test_passage_path(@test_passage) if @test_passage.time_is_up?
  end

  def result
  end

  
  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed? 
      if @test_passage.success? && !@test_passage.time_is_up?
        current_user.badges << BadgeService.new(@test_passage).call
      end

      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    service = GistQuestionService.new(@test_passage.current_question)
    result = service.call

    if service.success?
      current_user.gists.create!(question: @test_passage.current_question,
                                 url: result.html_url)
      flash[:notice] = "#{t('.success')} #{view_context.link_to(t('.view_gist'),
                                            result.html_url,
                                            target: :_blank)}"
    else
      flash[:alert] = t('.failure')
    end

    redirect_to @test_passage
  end


  private

  def create_gist(result)
    current_user.gists.create(
      author_id: current_user.id,
      question_id: @test_passage.current_question.id,
      url: result.html_url
    )
  end

  def set_test_passage
    if TestPassage.exists?(params[:id])
      @test_passage = TestPassage.find(params[:id])
    else
      flash[:alert] = t('.test_not_found')
      redirect_to root_path
    end
  end
    
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>
  <h2>
    <% if @test_passage.success? %>
      <p color: rgb(255, 0, 0)>
        <%= t('.result') %><span class="success"><%=@test_passage.percent_correct %>%</span>. <%= t('.success') %>
      </p>
    <% else %>
      <p color: rgb(0, 255, 0)>
         <%= t('.result') %><span class="fail"><%=@test_passage.percent_correct %>%</span>. <%= t('.fail') %>
      </p>
    <% end %>
</h2>

<p><%= link_to t('.link_back'), tests_path %></p>

app/views/test_passages/show.html.erb
<h1><%= t('.current_test', title: @test_passage.test.title) %></h1>
<p>
  <b><%= @test_passage.current_question.body %></b>
</p>

<p>
  <b>
    <%= t('.question_num') %><%= @test_passage.current_question_number %> <%= t('.from') %>
    <%= @test_passage.total_test_questions %>
  </b>
</p>

<div class="progress">
  <div class="progress-bar" id="progress-bar" data-progress="<%= @test_passage.percent_correct %>"
       aria-valuemax="100">
    <%= @test_passage.percent_correct %>
  </div>
</div>
 
<% if @test_passage.test.timer %>
  <b><%= t('.remaining_time') %>:</b>
  <%= content_tag :span, '', id: :timer, data: {timer: @test_passage.timer_finish.to_s} %>
  <%#= t('.minutes') %>
<% end %>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put,
              class: 'testpassage-form', data: { testpassage_id: @test_passage.id } do |form| %>
              
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= link_to 'Gist Question', gist_test_passage_path(@test_passage), method: :post %></p>
  <p><%= form.submit t('.next') %></p>
<% end %>